- name: Add docker repo
  include_tasks: "{{ item }}"
  with_first_found:
    - "docker_add_repo_{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "docker_add_repo_{{ ansible_distribution }}.yml"

- name: Install docker
  ansible.builtin.package:
    name: "{{ docker_package }}"
    state: latest
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
  loop_control:
    loop_var: docker_package

- name: Start docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
